"""Seed database with travel inventory concentrated in next 2 weeks."""

from datetime import datetime
from sqlmodel import Session, select
from db import create_db_and_tables, engine
from models.flight import Flight
from models.hotel import Hotel
from models.activity import Activity
from models.transport import Transport
from routers.auth import ensure_admin_user

# Today's date: April 2, 2026
# Next 2 weeks: April 2-16 (dense inventory)
# Future months: April 17+ to June (sparse inventory)

TODAY = datetime(2026, 4, 2)


def _d(month: int, day: int, hour: int = 0, minute: int = 0) -> datetime:
    return datetime(2026, month, day, hour, minute)


def seed() -> None:
    create_db_and_tables()

    with Session(engine) as session:
        # Clear existing inventory
        for item in session.exec(select(Flight)).all():
            session.delete(item)
        for item in session.exec(select(Hotel)).all():
            session.delete(item)
        for item in session.exec(select(Activity)).all():
            session.delete(item)
        for item in session.exec(select(Transport)).all():
            session.delete(item)
        session.commit()

        # =====================================================================
        # FLIGHTS — APRIL 2-16 (DENSE — 25 flights)
        # =====================================================================
        flights = [
            # April 3
            Flight(
                origin="Bangkok",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=_d(4, 3, 7, 0),
                arrival_time=_d(4, 3, 10, 15),
                price=185.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Bali",
                airline="Garuda Indonesia",
                departure_time=_d(4, 3, 9, 30),
                arrival_time=_d(4, 3, 12, 45),
                price=145.00,
                seats_available=55,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Phuket",
                airline="AirAsia",
                departure_time=_d(4, 3, 14, 0),
                arrival_time=_d(4, 3, 15, 10),
                price=68.00,
                seats_available=90,
                class_type="economy",
            ),
            # April 4
            Flight(
                origin="Bali",
                destination="Singapore",
                airline="Garuda Indonesia",
                departure_time=_d(4, 4, 6, 0),
                arrival_time=_d(4, 4, 9, 15),
                price=150.00,
                seats_available=45,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Phuket",
                airline="Thai Airways",
                departure_time=_d(4, 4, 8, 30),
                arrival_time=_d(4, 4, 9, 45),
                price=72.00,
                seats_available=30,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Kuala Lumpur",
                airline="Malaysia Airlines",
                departure_time=_d(4, 4, 11, 0),
                arrival_time=_d(4, 4, 12, 5),
                price=55.00,
                seats_available=80,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Bangkok",
                airline="Thai Airways",
                departure_time=_d(4, 4, 16, 0),
                arrival_time=_d(4, 4, 17, 15),
                price=70.00,
                seats_available=25,
                class_type="economy",
            ),
            # April 5
            Flight(
                origin="Bangkok",
                destination="Chiang Mai",
                airline="Bangkok Airways",
                departure_time=_d(4, 5, 7, 0),
                arrival_time=_d(4, 5, 8, 15),
                price=48.00,
                seats_available=100,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Singapore",
                airline="AirAsia",
                departure_time=_d(4, 5, 10, 30),
                arrival_time=_d(4, 5, 11, 35),
                price=52.00,
                seats_available=75,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Bangkok",
                airline="Singapore Airlines",
                departure_time=_d(4, 5, 15, 0),
                arrival_time=_d(4, 5, 18, 15),
                price=195.00,
                seats_available=35,
                class_type="economy",
            ),
            # April 6
            Flight(
                origin="Bali",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=_d(4, 6, 8, 0),
                arrival_time=_d(4, 6, 11, 30),
                price=125.00,
                seats_available=60,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Singapore",
                airline="Jetstar",
                departure_time=_d(4, 6, 13, 0),
                arrival_time=_d(4, 6, 16, 30),
                price=88.00,
                seats_available=50,
                class_type="economy",
            ),
            Flight(
                origin="Chiang Mai",
                destination="Bangkok",
                airline="Thai Airways",
                departure_time=_d(4, 6, 18, 0),
                arrival_time=_d(4, 6, 19, 15),
                price=45.00,
                seats_available=90,
                class_type="economy",
            ),
            # April 7
            Flight(
                origin="Singapore",
                destination="Phuket",
                airline="Scoot",
                departure_time=_d(4, 7, 9, 0),
                arrival_time=_d(4, 7, 12, 0),
                price=78.00,
                seats_available=70,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Kuala Lumpur",
                airline="Thai Airways",
                departure_time=_d(4, 7, 11, 30),
                arrival_time=_d(4, 7, 14, 45),
                price=155.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Bali",
                airline="AirAsia",
                departure_time=_d(4, 7, 17, 0),
                arrival_time=_d(4, 7, 20, 15),
                price=135.00,
                seats_available=55,
                class_type="economy",
            ),
            # April 8
            Flight(
                origin="Phuket",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=_d(4, 8, 7, 30),
                arrival_time=_d(4, 8, 8, 40),
                price=62.00,
                seats_available=85,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Chiang Mai",
                airline="Thai Airways",
                departure_time=_d(4, 8, 10, 0),
                arrival_time=_d(4, 8, 13, 0),
                price=175.00,
                seats_available=30,
                class_type="economy",
            ),
            Flight(
                origin="Bali",
                destination="Bangkok",
                airline="Garuda Indonesia",
                departure_time=_d(4, 8, 14, 0),
                arrival_time=_d(4, 8, 17, 30),
                price=165.00,
                seats_available=45,
                class_type="economy",
            ),
            # April 9
            Flight(
                origin="Bangkok",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=_d(4, 9, 6, 0),
                arrival_time=_d(4, 9, 9, 15),
                price=190.00,
                seats_available=35,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Phuket",
                airline="AirAsia",
                departure_time=_d(4, 9, 12, 0),
                arrival_time=_d(4, 9, 13, 10),
                price=65.00,
                seats_available=95,
                class_type="economy",
            ),
            Flight(
                origin="Chiang Mai",
                destination="Singapore",
                airline="Singapore Airlines",
                departure_time=_d(4, 9, 16, 30),
                arrival_time=_d(4, 9, 21, 0),
                price=220.00,
                seats_available=20,
                class_type="economy",
            ),
            # April 10
            Flight(
                origin="Phuket",
                destination="Bangkok",
                airline="Thai Airways",
                departure_time=_d(4, 10, 8, 0),
                arrival_time=_d(4, 10, 9, 15),
                price=68.00,
                seats_available=50,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Bali",
                airline="Garuda Indonesia",
                departure_time=_d(4, 10, 11, 0),
                arrival_time=_d(4, 10, 14, 15),
                price=148.00,
                seats_available=60,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Phuket",
                airline="Bangkok Airways",
                departure_time=_d(4, 10, 15, 0),
                arrival_time=_d(4, 10, 16, 15),
                price=75.00,
                seats_available=40,
                class_type="economy",
            ),
            # April 11
            Flight(
                origin="Kuala Lumpur",
                destination="Singapore",
                airline="Malaysia Airlines",
                departure_time=_d(4, 11, 8, 30),
                arrival_time=_d(4, 11, 9, 35),
                price=58.00,
                seats_available=70,
                class_type="economy",
            ),
            Flight(
                origin="Bali",
                destination="Singapore",
                airline="AirAsia",
                departure_time=_d(4, 11, 13, 0),
                arrival_time=_d(4, 11, 16, 15),
                price=142.00,
                seats_available=55,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Kuala Lumpur",
                airline="Jetstar",
                departure_time=_d(4, 11, 18, 0),
                arrival_time=_d(4, 11, 19, 10),
                price=60.00,
                seats_available=80,
                class_type="economy",
            ),
            # April 12
            Flight(
                origin="Singapore",
                destination="Bangkok",
                airline="Singapore Airlines",
                departure_time=_d(4, 12, 7, 0),
                arrival_time=_d(4, 12, 10, 15),
                price=198.00,
                seats_available=30,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Chiang Mai",
                airline="Thai Airways",
                departure_time=_d(4, 12, 12, 0),
                arrival_time=_d(4, 12, 13, 15),
                price=50.00,
                seats_available=110,
                class_type="economy",
            ),
            # April 13
            Flight(
                origin="Kuala Lumpur",
                destination="Bali",
                airline="AirAsia",
                departure_time=_d(4, 13, 9, 0),
                arrival_time=_d(4, 13, 12, 15),
                price=130.00,
                seats_available=65,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Singapore",
                airline="Scoot",
                departure_time=_d(4, 13, 14, 0),
                arrival_time=_d(4, 13, 17, 30),
                price=92.00,
                seats_available=45,
                class_type="economy",
            ),
            # April 14
            Flight(
                origin="Singapore",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=_d(4, 14, 8, 0),
                arrival_time=_d(4, 14, 9, 5),
                price=55.00,
                seats_available=85,
                class_type="economy",
            ),
            Flight(
                origin="Bali",
                destination="Phuket",
                airline="Garuda Indonesia",
                departure_time=_d(4, 14, 11, 0),
                arrival_time=_d(4, 14, 14, 0),
                price=158.00,
                seats_available=35,
                class_type="economy",
            ),
            # April 15
            Flight(
                origin="Bangkok",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=_d(4, 15, 7, 30),
                arrival_time=_d(4, 15, 10, 45),
                price=188.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Chiang Mai",
                destination="Bangkok",
                airline="Bangkok Airways",
                departure_time=_d(4, 15, 14, 0),
                arrival_time=_d(4, 15, 15, 15),
                price=48.00,
                seats_available=100,
                class_type="economy",
            ),
            # April 16
            Flight(
                origin="Kuala Lumpur",
                destination="Singapore",
                airline="Malaysia Airlines",
                departure_time=_d(4, 16, 10, 0),
                arrival_time=_d(4, 16, 11, 5),
                price=56.00,
                seats_available=75,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Bangkok",
                airline="Thai Airways",
                departure_time=_d(4, 16, 16, 30),
                arrival_time=_d(4, 16, 17, 45),
                price=72.00,
                seats_available=55,
                class_type="economy",
            ),
        ]
        session.add_all(flights)

        # =====================================================================
        # FLIGHTS — APRIL 17+ (SPARSE — 12 flights across rest of April-June)
        # =====================================================================
        future_flights = [
            Flight(
                origin="Singapore",
                destination="Bangkok",
                airline="Singapore Airlines",
                departure_time=_d(4, 20, 8, 0),
                arrival_time=_d(4, 20, 11, 15),
                price=205.00,
                seats_available=30,
                class_type="economy",
            ),
            Flight(
                origin="Bali",
                destination="Singapore",
                airline="Garuda Indonesia",
                departure_time=_d(4, 25, 10, 0),
                arrival_time=_d(4, 25, 13, 15),
                price=155.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Singapore",
                airline="Jetstar",
                departure_time=_d(5, 1, 9, 0),
                arrival_time=_d(5, 1, 12, 30),
                price=98.00,
                seats_available=50,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Kuala Lumpur",
                airline="Thai Airways",
                departure_time=_d(5, 5, 7, 30),
                arrival_time=_d(5, 5, 10, 45),
                price=165.00,
                seats_available=35,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Phuket",
                airline="AirAsia",
                departure_time=_d(5, 10, 14, 0),
                arrival_time=_d(5, 10, 15, 10),
                price=72.00,
                seats_available=80,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Chiang Mai",
                airline="Thai Airways",
                departure_time=_d(5, 15, 11, 0),
                arrival_time=_d(5, 15, 14, 0),
                price=185.00,
                seats_available=25,
                class_type="economy",
            ),
            Flight(
                origin="Bali",
                destination="Bangkok",
                airline="Garuda Indonesia",
                departure_time=_d(5, 20, 8, 0),
                arrival_time=_d(5, 20, 11, 30),
                price=175.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Chiang Mai",
                destination="Singapore",
                airline="Singapore Airlines",
                departure_time=_d(5, 25, 15, 0),
                arrival_time=_d(5, 25, 19, 30),
                price=235.00,
                seats_available=20,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=_d(6, 1, 10, 0),
                arrival_time=_d(6, 1, 11, 10),
                price=68.00,
                seats_available=90,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=_d(6, 5, 9, 0),
                arrival_time=_d(6, 5, 12, 15),
                price=198.00,
                seats_available=35,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Bali",
                airline="Garuda Indonesia",
                departure_time=_d(6, 10, 13, 0),
                arrival_time=_d(6, 10, 16, 15),
                price=158.00,
                seats_available=45,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Bangkok",
                airline="AirAsia",
                departure_time=_d(6, 15, 16, 0),
                arrival_time=_d(6, 15, 19, 15),
                price=145.00,
                seats_available=55,
                class_type="economy",
            ),
        ]
        session.add_all(future_flights)

        # =====================================================================
        # HOTELS — APRIL 2-16 (DENSE — 20 hotels)
        # =====================================================================
        hotels = [
            Hotel(
                name="Mandarin Oriental Bangkok",
                location="48 Oriental Ave",
                city="Bangkok",
                stars=5,
                price_per_night=320.00,
                rooms_available=8,
                amenities="pool,spa,gym,restaurant,river view",
            ),
            Hotel(
                name="The Peninsula Bangkok",
                location="333 Charoen Nakhon Rd",
                city="Bangkok",
                stars=5,
                price_per_night=295.00,
                rooms_available=10,
                amenities="pool,spa,river views,restaurants,shuttle boat",
            ),
            Hotel(
                name="ibis Bangkok Sukhumvit",
                location="27 Sukhumvit Soi 4",
                city="Bangkok",
                stars=3,
                price_per_night=58.00,
                rooms_available=40,
                amenities="wifi,breakfast,24h reception",
            ),
            Hotel(
                name="Khaosan Road Hostel",
                location="84 Khaosan Rd",
                city="Bangkok",
                stars=2,
                price_per_night=18.00,
                rooms_available=50,
                amenities="wifi,bar,24h reception,lockers",
            ),
            Hotel(
                name="Marina Bay Sands",
                location="10 Bayfront Ave",
                city="Singapore",
                stars=5,
                price_per_night=550.00,
                rooms_available=5,
                amenities="infinity pool,casino,mall,3 restaurants,sky park",
            ),
            Hotel(
                name="The St. Regis Singapore",
                location="29 Tanglin Rd",
                city="Singapore",
                stars=5,
                price_per_night=420.00,
                rooms_available=8,
                amenities="pool,spa,restaurant,butler service,gardens",
            ),
            Hotel(
                name="Hotel Indigo Singapore",
                location="2 Tiong Bahru Rd",
                city="Singapore",
                stars=4,
                price_per_night=175.00,
                rooms_available=20,
                amenities="pool,restaurant,rooftop bar,wifi",
            ),
            Hotel(
                name="Champion Hotel",
                location="1 Jalan dlrs",
                city="Singapore",
                stars=3,
                price_per_night=95.00,
                rooms_available=35,
                amenities="wifi,breakfast,central location,air conditioning",
            ),
            Hotel(
                name="The Mulia Bali",
                location="Jl. Raya Nusa Dua Selatan",
                city="Bali",
                stars=5,
                price_per_night=450.00,
                rooms_available=6,
                amenities="private beach,pool,spa,multiple restaurants,butler service",
            ),
            Hotel(
                name="Seminyak Garden Suites",
                location="Jl. Drupadi 18, Seminyak",
                city="Bali",
                stars=3,
                price_per_night=60.00,
                rooms_available=30,
                amenities="pool,wifi,breakfast,shuttle,garden",
            ),
            Hotel(
                name="Ubud Rice Terrace Guesthouse",
                location="Tegallalang, Ubud",
                city="Bali",
                stars=2,
                price_per_night=28.00,
                rooms_available=25,
                amenities="wifi,breakfast,rice terrace views,bicycle rental",
            ),
            Hotel(
                name="Patong Bay Guesthouse",
                location="118/3 Thaweewong Rd, Patong",
                city="Phuket",
                stars=2,
                price_per_night=25.00,
                rooms_available=35,
                amenities="wifi,fan rooms,shared kitchen,beach nearby",
            ),
            Hotel(
                name="Trisara Phuket",
                location="60/1 Moo 6, Srisoonthorn Rd",
                city="Phuket",
                stars=5,
                price_per_night=380.00,
                rooms_available=8,
                amenities="private pool villas,beach,spa,restaurant",
            ),
            Hotel(
                name="Phuket Grand Seaview",
                location="123 Kata Beach Rd, Kata",
                city="Phuket",
                stars=4,
                price_per_night=140.00,
                rooms_available=25,
                amenities="pool,spa,gym,2 restaurants,beach shuttle,wifi",
            ),
            Hotel(
                name="The RuMa Hotel Kuala Lumpur",
                location="7 Jalan Kia Peng",
                city="Kuala Lumpur",
                stars=5,
                price_per_night=280.00,
                rooms_available=12,
                amenities="pool,spa,gym,restaurant,bar,KLCC views",
            ),
            Hotel(
                name="Bukit Bintang Budget Inn",
                location="Jl. Bukit Bintang 44",
                city="Kuala Lumpur",
                stars=2,
                price_per_night=22.00,
                rooms_available=48,
                amenities="wifi,air conditioning,24h reception,near metro",
            ),
            Hotel(
                name="Sala Lanna Chiang Mai",
                location="49/9 Charoenrat Rd",
                city="Chiang Mai",
                stars=4,
                price_per_night=115.00,
                rooms_available=18,
                amenities="pool,restaurant,bar,bicycle rental,river view,wifi",
            ),
            Hotel(
                name="Chiangmai Heritage House",
                location="7 Moonmuang Rd, Old City",
                city="Chiang Mai",
                stars=3,
                price_per_night=52.00,
                rooms_available=22,
                amenities="pool,breakfast,wifi,bicycle rental,garden",
            ),
            Hotel(
                name="Nusa Dua Beach Villas",
                location="Jl. Pantai Mengiat, Nusa Dua",
                city="Bali",
                stars=4,
                price_per_night=185.00,
                rooms_available=14,
                amenities="private pool,beach access,spa,restaurant,wifi",
            ),
            Hotel(
                name="Lantern Hoi An Hotel",
                location="34 Le Loi St, Hoi An",
                city="Hoi An",
                stars=3,
                price_per_night=45.00,
                rooms_available=20,
                amenities="pool,breakfast,wifi,laundry,bicycle rental",
            ),
        ]
        session.add_all(hotels)

        # =====================================================================
        # HOTELS — APRIL 17+ (SPARSE — 8 hotels)
        # =====================================================================
        future_hotels = [
            Hotel(
                name="The Fullerton Hotel Singapore",
                location="1 Fullerton Square",
                city="Singapore",
                stars=5,
                price_per_night=480.00,
                rooms_available=6,
                amenities="pool,spa,gym,multiple restaurants,harbour views",
            ),
            Hotel(
                name="Capri by Fraser Bali",
                location="Jl. Pantai Bale",
                city="Bali",
                stars=4,
                price_per_night=135.00,
                rooms_available=20,
                amenities="pool,spa,restaurant,wifi,beach access",
            ),
            Hotel(
                name="Novotel Phuket Kamala Beach",
                location="Moo 5, Kamala",
                city="Phuket",
                stars=4,
                price_per_night=165.00,
                rooms_available=28,
                amenities="pool,spa,restaurant,beachfront,wifi",
            ),
            Hotel(
                name="MiKa Hotel Bangkok",
                location="18 Sukhumvit Soi 8",
                city="Bangkok",
                stars=4,
                price_per_night=125.00,
                rooms_available=22,
                amenities="pool,gym,restaurant,wifi,near BTS",
            ),
            Hotel(
                name="One Farrer Hotel",
                location="1 Farrer Park Station Rd",
                city="Singapore",
                stars=5,
                price_per_night=395.00,
                rooms_available=10,
                amenities="pool,spa,3 restaurants,wifi,MRT access",
            ),
            Hotel(
                name="Anantara Seminyak Bali",
                location="Jl. Abimanyu, Seminyak",
                city="Bali",
                stars=5,
                price_per_night=380.00,
                rooms_available=8,
                amenities="pool,spa,restaurant,beachfront,rooftop bar",
            ),
            Hotel(
                name="Hyatt Regency Phuket",
                location="16/12 Moo 6, Kamala",
                city="Phuket",
                stars=5,
                price_per_night=320.00,
                rooms_available=12,
                amenities="pool,spa,gym,restaurant,cliff views",
            ),
            Hotel(
                name="Mandarin Oriental KL",
                location="Jalan Pinang",
                city="Kuala Lumpur",
                stars=5,
                price_per_night=350.00,
                rooms_available=9,
                amenities="pool,spa,fine dining,concierge,KLCC views",
            ),
        ]
        session.add_all(future_hotels)

        # =====================================================================
        # ACTIVITIES — APRIL 2-16 (DENSE — 25 activities)
        # =====================================================================
        activities = [
            # Bangkok
            Activity(
                name="Grand Palace & Emerald Buddha Tour",
                city="Bangkok",
                description="Guided tour of the iconic Grand Palace and Temple of the Emerald Buddha.",
                duration_hours=3.5,
                price=38.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Muay Thai Training Class",
                city="Bangkok",
                description="Two-hour beginner Muay Thai session with a professional trainer.",
                duration_hours=2.0,
                price=25.00,
                category="adventure",
                availability="monday-friday",
            ),
            Activity(
                name="Bangkok Rooftop Bar Sunset",
                city="Bangkok",
                description="Sunset drinks at an iconic open-air rooftop bar with city panorama.",
                duration_hours=2.5,
                price=40.00,
                category="nightlife",
                availability="daily",
            ),
            Activity(
                name="Thai Cooking Class Bangkok",
                city="Bangkok",
                description="Half-day cooking class at a local kitchen — market visit + 5 dishes.",
                duration_hours=4.5,
                price=45.00,
                category="food",
                availability="daily",
            ),
            # Singapore
            Activity(
                name="Singapore Street Food Night Tour",
                city="Singapore",
                description="Explore hawker centres and hidden eateries with a local food expert.",
                duration_hours=3.5,
                price=85.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Sentosa Island Beach Club",
                city="Singapore",
                description="Full-day access to Sentosa beach club with water sports and beach bar.",
                duration_hours=8.0,
                price=65.00,
                category="water sports",
                availability="daily",
            ),
            Activity(
                name="Singapore Night Safari",
                city="Singapore",
                description="Guided tram and walking tour through the nocturnal wildlife park.",
                duration_hours=3.5,
                price=58.00,
                category="nature",
                availability="daily",
            ),
            # Bali
            Activity(
                name="Ubud Rice Terrace Cycling",
                city="Bali",
                description="Cycle through Tegallalang rice terraces with local guide and lunch.",
                duration_hours=5.0,
                price=55.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Bali Volcano Sunrise Trek",
                city="Bali",
                description="Night trek to Mount Batur summit to watch sunrise over the caldera.",
                duration_hours=7.0,
                price=65.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Balinese Spa & Wellness Ritual",
                city="Bali",
                description="Three-hour traditional Balinese spa: scrub, massage, and flower bath.",
                duration_hours=3.0,
                price=50.00,
                category="wellness",
                availability="daily",
            ),
            Activity(
                name="Seminyak Sunset Surf Lesson",
                city="Bali",
                description="Two-hour beginner surf lesson on Seminyak Beach with certified instructors.",
                duration_hours=2.0,
                price=35.00,
                category="water sports",
                availability="daily",
            ),
            # Phuket
            Activity(
                name="Phi Phi Island Snorkeling Day Trip",
                city="Phuket",
                description="Speedboat tour to Phi Phi Islands with snorkeling, kayaking, and beach time.",
                duration_hours=9.0,
                price=78.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="James Bond Island Tour",
                city="Phuket",
                description="Speedboat to Phang Nga Bay and Koh Tapu with sea canoeing.",
                duration_hours=6.0,
                price=68.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Phuket Rooftop Bar Nightlife",
                city="Phuket",
                description="Guided nightlife crawl hitting 4 rooftop bars in Patong.",
                duration_hours=4.0,
                price=45.00,
                category="nightlife",
                availability="weekends",
            ),
            # Kuala Lumpur
            Activity(
                name="Batu Caves & KL City Highlights",
                city="Kuala Lumpur",
                description="Visit the famous Batu Caves and explore KL's colonial quarter.",
                duration_hours=6.0,
                price=42.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="KL Street Art Walk",
                city="Kuala Lumpur",
                description="Walking tour of Klang Valley's vibrant murals with audio guide.",
                duration_hours=2.0,
                price=12.00,
                category="culture",
                availability="daily",
            ),
            # Chiang Mai
            Activity(
                name="Elephant Sanctuary Half-Day",
                city="Chiang Mai",
                description="Ethical elephant experience: feed, bathe, and walk with rescued elephants.",
                duration_hours=4.5,
                price=88.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Chiang Mai Night Bazaar Food Tour",
                city="Chiang Mai",
                description="Walk the Night Bazaar sampling khao soi, sai oua, and mango sticky rice.",
                duration_hours=3.0,
                price=30.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Thai Cooking Class Chiang Mai",
                city="Chiang Mai",
                description="Market visit + cook 5 dishes at a family farm.",
                duration_hours=4.0,
                price=40.00,
                category="food",
                availability="daily",
            ),
            # Hoi An
            Activity(
                name="Lantern Making Workshop",
                city="Hoi An",
                description="Learn to craft a traditional silk lantern from a local artisan.",
                duration_hours=2.0,
                price=18.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Hoi An Boat Ride & Cooking Class",
                city="Hoi An",
                description="Cruise Thu Bon River, visit herb island, then cook Vietnamese dishes.",
                duration_hours=6.0,
                price=55.00,
                category="food",
                availability="daily",
            ),
            # Multi-city / varied
            Activity(
                name="Mekong Delta Day Trip",
                city="Ho Chi Minh City",
                description="Full-day boat tour through the Mekong Delta with floating markets.",
                duration_hours=8.0,
                price=45.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Halong Bay Sunset Kayaking",
                city="Hanoi",
                description="Day trip to Halong Bay with guided kayaking through limestone caves.",
                duration_hours=8.0,
                price=95.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Hanoi Old Quarter Walking Tour",
                city="Hanoi",
                description="Explore the 36 ancient trade streets with a knowledgeable local guide.",
                duration_hours=3.0,
                price=20.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Bangkok Canal Boat Tour",
                city="Bangkok",
                description="Longtail boat ride through Bangkok's canals, floating markets, and temples.",
                duration_hours=3.0,
                price=28.00,
                category="culture",
                availability="daily",
            ),
        ]
        session.add_all(activities)

        # =====================================================================
        # ACTIVITIES — APRIL 17+ (SPARSE — 10 activities)
        # =====================================================================
        future_activities = [
            Activity(
                name="Bangkok Temple & River Tour",
                city="Bangkok",
                description="Visit Wat Arun, Wat Pho, and cruise the Chao Phraya River.",
                duration_hours=4.0,
                price=35.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Singapore Gardens by the Bay",
                city="Singapore",
                description="Explore the Supertree Grove, Cloud Forest, and Flower Dome.",
                duration_hours=4.0,
                price=42.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Bali Water Sports Combo",
                city="Bali",
                description="Jet ski, parasailing, banana boat, and donut ride at Tanjung Benoa.",
                duration_hours=4.0,
                price=75.00,
                category="water sports",
                availability="daily",
            ),
            Activity(
                name="Phi Phi overnight stay",
                city="Phuket",
                description="Overnight on Phi Phi Don with sunset dinner and morning snorkeling.",
                duration_hours=24.0,
                price=150.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="KL Tower Observation Deck",
                city="Kuala Lumpur",
                description="Skip-the-line ticket to the KL Tower deck for 360-degree city views.",
                duration_hours=2.0,
                price=35.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Chiang Mai Doi Suthep Temple",
                city="Chiang Mai",
                description="Visit the sacred Doi Suthep temple on the mountain with panoramic views.",
                duration_hours=3.0,
                price=25.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Hoi An Ancient Town Walk",
                city="Hoi An",
                description="Guided walk through the UNESCO-listed Old Town with lantern-making.",
                duration_hours=3.0,
                price=22.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Bangkok Chatuchak Weekend Market",
                city="Bangkok",
                description="Navigate the massive weekend market with a local guide.",
                duration_hours=3.0,
                price=18.00,
                category="culture",
                availability="saturday-sunday",
            ),
            Activity(
                name="Singapore Universal Studios",
                city="Singapore",
                description="Full-day access to Universal Studios Singapore with express pass.",
                duration_hours=8.0,
                price=110.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Bali Sacred Monkey Forest",
                city="Bali",
                description="Visit the Ubud Monkey Forest and surrounding temples.",
                duration_hours=2.5,
                price=15.00,
                category="nature",
                availability="daily",
            ),
        ]
        session.add_all(future_activities)

        # =====================================================================
        # TRANSPORT — APRIL 2-16 (DENSE — 18 transport options)
        # =====================================================================
        transports = [
            # April 3
            Transport(
                type="ferry",
                origin="Singapore",
                destination="Batam",
                price=28.00,
                capacity=200,
                departure_time=_d(4, 3, 9, 0),
                arrival_time=_d(4, 3, 10, 0),
            ),
            Transport(
                type="train",
                origin="Bangkok",
                destination="Chiang Mai",
                price=22.00,
                capacity=120,
                departure_time=_d(4, 3, 18, 0),
                arrival_time=_d(4, 4, 7, 0),
            ),
            # April 4
            Transport(
                type="bus",
                origin="Kuala Lumpur",
                destination="Singapore",
                price=18.00,
                capacity=45,
                departure_time=_d(4, 4, 8, 0),
                arrival_time=_d(4, 4, 13, 30),
            ),
            Transport(
                type="car",
                origin="Bali Airport",
                destination="Ubud",
                price=25.00,
                capacity=4,
                departure_time=_d(4, 4, 15, 0),
                arrival_time=_d(4, 4, 16, 30),
            ),
            # April 5
            Transport(
                type="ferry",
                origin="Phuket",
                destination="Koh Samui",
                price=45.00,
                capacity=150,
                departure_time=_d(4, 5, 7, 30),
                arrival_time=_d(4, 5, 13, 0),
            ),
            Transport(
                type="bus",
                origin="Bangkok",
                destination="Pattaya",
                price=5.00,
                capacity=45,
                departure_time=_d(4, 5, 7, 0),
                arrival_time=_d(4, 5, 9, 0),
            ),
            # April 6
            Transport(
                type="ferry",
                origin="Bali",
                destination="Lombok",
                price=12.00,
                capacity=60,
                departure_time=_d(4, 6, 8, 30),
                arrival_time=_d(4, 6, 10, 30),
            ),
            Transport(
                type="train",
                origin="Singapore",
                destination="Kuala Lumpur",
                price=35.00,
                capacity=200,
                departure_time=_d(4, 6, 10, 0),
                arrival_time=_d(4, 6, 14, 30),
            ),
            # April 7
            Transport(
                type="ferry",
                origin="Phuket",
                destination="Krabi",
                price=15.00,
                capacity=50,
                departure_time=_d(4, 7, 9, 0),
                arrival_time=_d(4, 7, 10, 30),
            ),
            Transport(
                type="bus",
                origin="Chiang Mai",
                destination="Pai",
                price=12.00,
                capacity=30,
                departure_time=_d(4, 7, 14, 0),
                arrival_time=_d(4, 7, 17, 0),
            ),
            # April 8
            Transport(
                type="car",
                origin="Bali Airport",
                destination="Seminyak",
                price=20.00,
                capacity=4,
                departure_time=_d(4, 8, 12, 0),
                arrival_time=_d(4, 8, 13, 0),
            ),
            Transport(
                type="train",
                origin="Bangkok",
                destination="Ayutthaya",
                price=3.00,
                capacity=150,
                departure_time=_d(4, 8, 8, 0),
                arrival_time=_d(4, 8, 9, 0),
            ),
            # April 9
            Transport(
                type="ferry",
                origin="Singapore",
                destination="Batam",
                price=28.00,
                capacity=200,
                departure_time=_d(4, 9, 15, 0),
                arrival_time=_d(4, 9, 16, 0),
            ),
            Transport(
                type="bus",
                origin="Kuala Lumpur",
                destination="Penang",
                price=15.00,
                capacity=45,
                departure_time=_d(4, 9, 9, 0),
                arrival_time=_d(4, 9, 15, 0),
            ),
            # April 10
            Transport(
                type="train",
                origin="Singapore",
                destination="Kuala Lumpur",
                price=35.00,
                capacity=200,
                departure_time=_d(4, 10, 8, 0),
                arrival_time=_d(4, 10, 12, 30),
            ),
            Transport(
                type="ferry",
                origin="Bali",
                destination="Nusa Penida",
                price=10.00,
                capacity=80,
                departure_time=_d(4, 10, 9, 0),
                arrival_time=_d(4, 10, 10, 0),
            ),
            # April 11
            Transport(
                type="bus",
                origin="Bangkok",
                destination="Kanchanaburi",
                price=6.00,
                capacity=40,
                departure_time=_d(4, 11, 8, 0),
                arrival_time=_d(4, 11, 10, 30),
            ),
            Transport(
                type="car",
                origin="Phuket Airport",
                destination="Patong",
                price=22.00,
                capacity=4,
                departure_time=_d(4, 11, 14, 0),
                arrival_time=_d(4, 11, 15, 15),
            ),
            # April 12
            Transport(
                type="ferry",
                origin="Koh Samui",
                destination="Koh Phangan",
                price=8.00,
                capacity=100,
                departure_time=_d(4, 12, 10, 0),
                arrival_time=_d(4, 12, 11, 0),
            ),
            Transport(
                type="train",
                origin="Kuala Lumpur",
                destination="Singapore",
                price=38.00,
                capacity=200,
                departure_time=_d(4, 12, 16, 0),
                arrival_time=_d(4, 12, 20, 30),
            ),
        ]
        session.add_all(transports)

        # =====================================================================
        # TRANSPORT — APRIL 17+ (SPARSE — 8 options)
        # =====================================================================
        future_transports = [
            Transport(
                type="ferry",
                origin="Singapore",
                destination="Batam",
                price=28.00,
                capacity=200,
                departure_time=_d(4, 20, 9, 0),
                arrival_time=_d(4, 20, 10, 0),
            ),
            Transport(
                type="train",
                origin="Bangkok",
                destination="Chiang Mai",
                price=25.00,
                capacity=120,
                departure_time=_d(4, 25, 18, 0),
                arrival_time=_d(4, 26, 7, 0),
            ),
            Transport(
                type="bus",
                origin="Kuala Lumpur",
                destination="Singapore",
                price=20.00,
                capacity=45,
                departure_time=_d(5, 1, 8, 0),
                arrival_time=_d(5, 1, 13, 30),
            ),
            Transport(
                type="ferry",
                origin="Phuket",
                destination="Koh Samui",
                price=48.00,
                capacity=150,
                departure_time=_d(5, 5, 7, 30),
                arrival_time=_d(5, 5, 13, 0),
            ),
            Transport(
                type="car",
                origin="Bali Airport",
                destination="Ubud",
                price=28.00,
                capacity=4,
                departure_time=_d(5, 10, 12, 0),
                arrival_time=_d(5, 10, 13, 30),
            ),
            Transport(
                type="train",
                origin="Singapore",
                destination="Kuala Lumpur",
                price=38.00,
                capacity=200,
                departure_time=_d(5, 15, 10, 0),
                arrival_time=_d(5, 15, 14, 30),
            ),
            Transport(
                type="bus",
                origin="Chiang Mai",
                destination="Bangkok",
                price=18.00,
                capacity=45,
                departure_time=_d(5, 20, 8, 0),
                arrival_time=_d(5, 20, 14, 0),
            ),
            Transport(
                type="ferry",
                origin="Bali",
                destination="Lombok",
                price=15.00,
                capacity=60,
                departure_time=_d(6, 1, 9, 0),
                arrival_time=_d(6, 1, 11, 0),
            ),
        ]
        session.add_all(future_transports)

        session.commit()
        ensure_admin_user(session)
        print("Seed complete.")
        print(f"  Flights: {len(flights) + len(future_flights)} (25 dense + 12 sparse)")
        print(f"  Hotels: {len(hotels) + len(future_hotels)} (20 dense + 8 sparse)")
        print(
            f"  Activities: {len(activities) + len(future_activities)} (25 dense + 10 sparse)"
        )
        print(
            f"  Transport: {len(transports) + len(future_transports)} (18 dense + 8 sparse)"
        )


if __name__ == "__main__":
    seed()
