from sqlmodel import Session, select
from db import create_db_and_tables, engine
from models.visa import VisaRequirement


VISA_DATA = [
    # Myanmar passport holders
    (
        "Myanmar",
        "Thailand",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Tourist visa-free",
    ),
    (
        "Myanmar",
        "Singapore",
        True,
        False,
        "Apply at embassy",
        30,
        "Tourist visa required",
    ),
    (
        "Myanmar",
        "Malaysia",
        True,
        False,
        "Apply at embassy",
        30,
        "Tourist visa required",
    ),
    (
        "Myanmar",
        "Indonesia",
        True,
        False,
        "eVisa available: https://evisa.imigration.go.id",
        30,
        "Tourist visa required",
    ),
    (
        "Myanmar",
        "Vietnam",
        True,
        False,
        "eVisa available: https://evisa.vietnamimigration.vn",
        45,
        "Tourist eVisa",
    ),
    (
        "Myanmar",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Tourist visa-free",
    ),
    (
        "Myanmar",
        "Laos",
        True,
        False,
        "Visa on arrival available",
        30,
        "Tourist visa on arrival",
    ),
    (
        "Myanmar",
        "Philippines",
        True,
        False,
        "Apply at embassy",
        30,
        "Tourist visa required",
    ),
    (
        "Myanmar",
        "Japan",
        True,
        False,
        "Apply at embassy, 5-7 days processing",
        90,
        "Tourist visa required",
    ),
    (
        "Myanmar",
        "South Korea",
        True,
        False,
        "Apply at embassy",
        90,
        "Tourist visa required",
    ),
    ("Myanmar", "China", True, False, "Apply at embassy", 60, "Tourist visa required"),
    ("Myanmar", "Taiwan", True, False, "Apply at embassy", 30, "Tourist visa required"),
    # Singapore passport holders
    ("Singapore", "Thailand", False, False, None, 30, "Visa-free"),
    (
        "Singapore",
        "Myanmar",
        False,
        True,
        "Visa on arrival, 28 days",
        28,
        "Tourist visa on arrival",
    ),
    ("Singapore", "Malaysia", False, False, None, 90, "Visa-free"),
    (
        "Singapore",
        "Indonesia",
        False,
        False,
        "Visa-free for social/tourist",
        30,
        "Visa-free",
    ),
    ("Singapore", "Vietnam", False, False, "eVisa available", 45, "Visa-free or eVisa"),
    (
        "Singapore",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Singapore",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Singapore", "Philippines", False, False, None, 30, "Visa-free"),
    ("Singapore", "Japan", False, False, "Visa-free for tourism", 90, "Visa-free"),
    (
        "Singapore",
        "South Korea",
        False,
        False,
        "K-ETA required online",
        90,
        "K-ETA required",
    ),
    (
        "Singapore",
        "China",
        True,
        False,
        "Visa required, group visa available",
        60,
        "Visa required",
    ),
    ("Singapore", "Taiwan", False, False, None, 90, "Visa-free"),
    # Thailand passport holders
    ("Thailand", "Singapore", False, False, None, 30, "Visa-free"),
    (
        "Thailand",
        "Myanmar",
        True,
        False,
        "eVisa available",
        28,
        "Tourist visa required",
    ),
    ("Thailand", "Malaysia", False, False, None, 90, "Visa-free"),
    ("Thailand", "Indonesia", False, False, None, 30, "Visa-free"),
    ("Thailand", "Vietnam", False, False, "eVisa available", 45, "Visa-free or eVisa"),
    (
        "Thailand",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Thailand",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Thailand", "Philippines", False, False, None, 30, "Visa-free"),
    ("Thailand", "Japan", False, False, None, 90, "Visa-free"),
    ("Thailand", "South Korea", False, False, "K-ETA required", 90, "K-ETA required"),
    ("Thailand", "China", True, False, "Visa required", 60, "Visa required"),
    ("Thailand", "Taiwan", False, False, None, 90, "Visa-free"),
    # Malaysia passport holders
    ("Malaysia", "Thailand", False, False, None, 30, "Visa-free"),
    ("Malaysia", "Singapore", False, False, None, 30, "Visa-free"),
    (
        "Malaysia",
        "Myanmar",
        True,
        False,
        "eVisa available",
        28,
        "Tourist visa required",
    ),
    ("Malaysia", "Indonesia", False, False, None, 30, "Visa-free"),
    ("Malaysia", "Vietnam", False, False, "eVisa available", 45, "Visa-free or eVisa"),
    (
        "Malaysia",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Malaysia",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Malaysia", "Philippines", False, False, None, 30, "Visa-free"),
    ("Malaysia", "Japan", False, False, None, 90, "Visa-free"),
    ("Malaysia", "South Korea", False, False, "K-ETA required", 90, "K-ETA required"),
    (
        "Malaysia",
        "China",
        False,
        False,
        "15-day visa-free transit",
        15,
        "Visa-free transit",
    ),
    ("Malaysia", "Taiwan", False, False, None, 90, "Visa-free"),
    # Indonesian passport holders
    ("Indonesia", "Thailand", False, False, None, 30, "Visa-free"),
    ("Indonesia", "Singapore", False, False, None, 30, "Visa-free"),
    ("Indonesia", "Malaysia", False, False, None, 90, "Visa-free"),
    (
        "Indonesia",
        "Myanmar",
        True,
        False,
        "eVisa available",
        28,
        "Tourist visa required",
    ),
    ("Indonesia", "Vietnam", False, False, "eVisa available", 45, "Visa-free or eVisa"),
    (
        "Indonesia",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Indonesia",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Indonesia", "Philippines", False, False, None, 30, "Visa-free"),
    (
        "Indonesia",
        "Japan",
        True,
        False,
        "Visa required, apply at embassy",
        90,
        "Tourist visa required",
    ),
    ("Indonesia", "South Korea", False, False, "K-ETA required", 90, "K-ETA required"),
    ("Indonesia", "China", True, False, "Visa required", 60, "Visa required"),
    (
        "Indonesia",
        "Taiwan",
        True,
        False,
        "Apply at embassy",
        30,
        "Tourist visa required",
    ),
    # Vietnamese passport holders
    ("Vietnam", "Thailand", False, False, None, 30, "Visa-free"),
    ("Vietnam", "Singapore", False, False, None, 30, "Visa-free"),
    ("Vietnam", "Malaysia", False, False, None, 30, "Visa-free"),
    ("Vietnam", "Myanmar", True, False, "eVisa available", 28, "Tourist visa required"),
    ("Vietnam", "Indonesia", False, False, None, 30, "Visa-free"),
    (
        "Vietnam",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Vietnam", "Laos", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    (
        "Vietnam",
        "Philippines",
        True,
        False,
        "Visa required",
        30,
        "Tourist visa required",
    ),
    (
        "Vietnam",
        "Japan",
        True,
        False,
        "Visa required, apply at embassy",
        90,
        "Tourist visa required",
    ),
    (
        "Vietnam",
        "South Korea",
        True,
        False,
        "K-ETA or visa required",
        90,
        "K-ETA required",
    ),
    ("Vietnam", "China", True, False, "Visa required", 60, "Visa required"),
    ("Vietnam", "Taiwan", True, False, "Apply at embassy", 30, "Tourist visa required"),
    # Philippine passport holders
    ("Philippines", "Thailand", False, False, None, 30, "Visa-free"),
    ("Philippines", "Singapore", False, False, None, 30, "Visa-free"),
    ("Philippines", "Malaysia", False, False, None, 30, "Visa-free"),
    (
        "Philippines",
        "Myanmar",
        True,
        False,
        "eVisa available",
        28,
        "Tourist visa required",
    ),
    ("Philippines", "Indonesia", False, False, None, 30, "Visa-free"),
    (
        "Philippines",
        "Vietnam",
        False,
        False,
        "eVisa available",
        45,
        "Visa-free or eVisa",
    ),
    (
        "Philippines",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Philippines",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Philippines",
        "Japan",
        True,
        False,
        "Visa required, multiple entry available",
        90,
        "Tourist visa required",
    ),
    (
        "Philippines",
        "South Korea",
        True,
        False,
        "K-ETA or visa required",
        90,
        "K-ETA required",
    ),
    (
        "Philippines",
        "China",
        True,
        False,
        "Visa required, transit visa-free",
        7,
        "Transit visa-free",
    ),
    (
        "Philippines",
        "Taiwan",
        True,
        False,
        "Apply at embassy",
        30,
        "Tourist visa required",
    ),
    # USA passport holders
    ("USA", "Thailand", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("USA", "Singapore", False, False, None, 90, "Visa-free"),
    ("USA", "Malaysia", False, False, None, 90, "Visa-free"),
    ("USA", "Myanmar", True, False, "eVisa available", 28, "Tourist visa required"),
    ("USA", "Indonesia", False, False, "Visa-free for tourism", 30, "Visa-free"),
    ("USA", "Vietnam", True, False, "eVisa available", 45, "eVisa required"),
    ("USA", "Cambodia", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("USA", "Laos", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("USA", "Philippines", False, False, None, 30, "Visa-free"),
    ("USA", "Japan", False, False, None, 90, "Visa-free"),
    ("USA", "South Korea", False, False, "ESTA or visa-free", 90, "ESTA required"),
    ("USA", "China", True, False, "Visa required", 60, "Visa required"),
    ("USA", "Taiwan", False, False, None, 90, "Visa-free"),
    # UK passport holders
    ("UK", "Thailand", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("UK", "Singapore", False, False, None, 90, "Visa-free"),
    ("UK", "Malaysia", False, False, None, 90, "Visa-free"),
    ("UK", "Myanmar", True, False, "eVisa available", 28, "Tourist visa required"),
    ("UK", "Indonesia", False, False, "Visa-free for tourism", 30, "Visa-free"),
    ("UK", "Vietnam", True, False, "eVisa available", 45, "eVisa required"),
    ("UK", "Cambodia", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("UK", "Laos", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    ("UK", "Philippines", False, False, None, 30, "Visa-free"),
    ("UK", "Japan", False, False, None, 90, "Visa-free"),
    ("UK", "South Korea", False, False, "ETA required", 90, "K-ETA required"),
    ("UK", "China", True, False, "Visa required", 60, "Visa required"),
    ("UK", "Taiwan", False, False, None, 90, "Visa-free"),
    # Australian passport holders
    (
        "Australia",
        "Thailand",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Australia", "Singapore", False, False, None, 90, "Visa-free"),
    ("Australia", "Malaysia", False, False, None, 90, "Visa-free"),
    (
        "Australia",
        "Myanmar",
        True,
        False,
        "eVisa available",
        28,
        "Tourist visa required",
    ),
    ("Australia", "Indonesia", False, False, "Visa-free for tourism", 30, "Visa-free"),
    ("Australia", "Vietnam", True, False, "eVisa available", 45, "eVisa required"),
    (
        "Australia",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    (
        "Australia",
        "Laos",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("Australia", "Philippines", False, False, None, 30, "Visa-free"),
    ("Australia", "Japan", False, False, None, 90, "Visa-free"),
    ("Australia", "South Korea", False, False, "ETA required", 90, "K-ETA required"),
    ("Australia", "China", True, False, "Visa required", 60, "Visa required"),
    ("Australia", "Taiwan", False, False, None, 90, "Visa-free"),
    # Chinese passport holders
    ("China", "Thailand", True, False, "eVisa available", 60, "Tourist visa required"),
    ("China", "Singapore", True, False, "Visa required", 30, "Tourist visa required"),
    ("China", "Malaysia", True, False, "eVisa available", 30, "eVisa required"),
    ("China", "Myanmar", True, False, "eVisa available", 28, "Tourist visa required"),
    ("China", "Indonesia", True, False, "eVisa available", 30, "eVisa required"),
    (
        "China",
        "Vietnam",
        False,
        True,
        "Visa on arrival, 45 days",
        45,
        "Visa on arrival",
    ),
    (
        "China",
        "Cambodia",
        False,
        True,
        "Visa on arrival, 30 days",
        30,
        "Visa on arrival",
    ),
    ("China", "Laos", False, True, "Visa on arrival, 30 days", 30, "Visa on arrival"),
    (
        "China",
        "Philippines",
        True,
        False,
        "eVisa available",
        30,
        "Tourist visa required",
    ),
    (
        "China",
        "Japan",
        True,
        False,
        "Visa required, apply at embassy",
        90,
        "Tourist visa required",
    ),
    (
        "China",
        "South Korea",
        False,
        False,
        "Free visa for group tours",
        30,
        "Group visa-free",
    ),
    (
        "China",
        "Taiwan",
        True,
        False,
        "Permit required, not visa",
        30,
        "Travel permit required",
    ),
]


def seed_visa():
    create_db_and_tables()

    with Session(engine) as session:
        # Clear existing visa data
        for visa in session.exec(select(VisaRequirement)).all():
            session.delete(visa)
        session.commit()

        # Seed new visa data
        visas = []
        for data in VISA_DATA:
            visa = VisaRequirement(
                origin_country=data[0],
                destination_country=data[1],
                visa_required=data[2],
                visa_on_arrival=data[3],
                visa_eta=data[4],
                max_stay_days=data[5],
                notes=data[6],
            )
            visas.append(visa)

        session.add_all(visas)
        session.commit()

        count = len(session.exec(select(VisaRequirement)).all())
        print(f"Seeded: {count} visa requirements")


if __name__ == "__main__":
    seed_visa()
