from datetime import datetime
from sqlmodel import Session, select
from db import create_db_and_tables, engine
from models.flight import Flight
from models.hotel import Hotel
from models.activity import Activity
from models.transport import Transport


def seed() -> None:
    create_db_and_tables()

    with Session(engine) as session:
        # Clear existing data
        for flight in session.exec(select(Flight)).all():
            session.delete(flight)
        for hotel in session.exec(select(Hotel)).all():
            session.delete(hotel)
        for activity in session.exec(select(Activity)).all():
            session.delete(activity)
        for transport in session.exec(select(Transport)).all():
            session.delete(transport)
        session.commit()

        # Flights
        flights = [
            Flight(
                origin="Singapore",
                destination="Bangkok",
                airline="Singapore Airlines",
                departure_time=datetime(2026, 4, 10, 8, 0),
                arrival_time=datetime(2026, 4, 10, 9, 30),
                price=189.99,
                seats_available=42,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Bali",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 12, 14, 0),
                arrival_time=datetime(2026, 4, 12, 17, 15),
                price=95.50,
                seats_available=80,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Phuket",
                airline="Thai Airways",
                departure_time=datetime(2026, 4, 15, 10, 30),
                arrival_time=datetime(2026, 4, 15, 11, 45),
                price=75.00,
                seats_available=20,
                class_type="business",
            ),
            Flight(
                origin="Singapore",
                destination="Kuala Lumpur",
                airline="Malaysia Airlines",
                departure_time=datetime(2026, 4, 18, 7, 0),
                arrival_time=datetime(2026, 4, 18, 8, 10),
                price=130.00,
                seats_available=15,
                class_type="first",
            ),
            Flight(
                origin="Bali",
                destination="Singapore",
                airline="Garuda Indonesia",
                departure_time=datetime(2026, 4, 20, 16, 0),
                arrival_time=datetime(2026, 4, 20, 19, 30),
                price=210.00,
                seats_available=55,
                class_type="economy",
            ),
            # New flights
            Flight(
                origin="Bangkok",
                destination="Chiang Mai",
                airline="Bangkok Airways",
                departure_time=datetime(2026, 4, 10, 6, 30),
                arrival_time=datetime(2026, 4, 10, 7, 45),
                price=48.00,
                seats_available=120,
                class_type="economy",
            ),
            Flight(
                origin="Ho Chi Minh City",
                destination="Hanoi",
                airline="Vietnam Airlines",
                departure_time=datetime(2026, 4, 11, 9, 0),
                arrival_time=datetime(2026, 4, 11, 11, 10),
                price=55.00,
                seats_available=95,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Manila",
                airline="Cebu Pacific",
                departure_time=datetime(2026, 4, 12, 7, 15),
                arrival_time=datetime(2026, 4, 12, 11, 0),
                price=89.00,
                seats_available=150,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Ho Chi Minh City",
                airline="Thai Airways",
                departure_time=datetime(2026, 4, 13, 11, 0),
                arrival_time=datetime(2026, 4, 13, 12, 30),
                price=110.00,
                seats_available=30,
                class_type="business",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Jakarta",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 14, 13, 45),
                arrival_time=datetime(2026, 4, 14, 15, 0),
                price=62.00,
                seats_available=180,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Hanoi",
                airline="Singapore Airlines",
                departure_time=datetime(2026, 4, 15, 8, 30),
                arrival_time=datetime(2026, 4, 15, 11, 0),
                price=175.00,
                seats_available=60,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Yangon",
                airline="Bangkok Airways",
                departure_time=datetime(2026, 4, 16, 7, 0),
                arrival_time=datetime(2026, 4, 16, 8, 10),
                price=95.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Phuket",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=datetime(2026, 4, 17, 14, 30),
                arrival_time=datetime(2026, 4, 17, 18, 0),
                price=155.00,
                seats_available=25,
                class_type="business",
            ),
            Flight(
                origin="Manila",
                destination="Singapore",
                airline="Cebu Pacific",
                departure_time=datetime(2026, 4, 18, 20, 0),
                arrival_time=datetime(2026, 4, 18, 23, 45),
                price=78.00,
                seats_available=200,
                class_type="economy",
            ),
            Flight(
                origin="Jakarta",
                destination="Bali",
                airline="Garuda Indonesia",
                departure_time=datetime(2026, 4, 19, 6, 0),
                arrival_time=datetime(2026, 4, 19, 7, 15),
                price=38.00,
                seats_available=110,
                class_type="economy",
            ),
            Flight(
                origin="Hanoi",
                destination="Bangkok",
                airline="Vietnam Airlines",
                departure_time=datetime(2026, 4, 20, 10, 15),
                arrival_time=datetime(2026, 4, 20, 12, 0),
                price=130.00,
                seats_available=70,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Phnom Penh",
                airline="Singapore Airlines",
                departure_time=datetime(2026, 4, 21, 9, 30),
                arrival_time=datetime(2026, 4, 21, 11, 15),
                price=145.00,
                seats_available=50,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Chiang Mai",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 22, 17, 0),
                arrival_time=datetime(2026, 4, 22, 18, 30),
                price=72.00,
                seats_available=160,
                class_type="economy",
            ),
            Flight(
                origin="Bangkok",
                destination="Singapore",
                airline="Thai Airways",
                departure_time=datetime(2026, 4, 23, 7, 45),
                arrival_time=datetime(2026, 4, 23, 11, 15),
                price=420.00,
                seats_available=12,
                class_type="first",
            ),
            Flight(
                origin="Bali",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 24, 15, 30),
                arrival_time=datetime(2026, 4, 24, 18, 45),
                price=85.00,
                seats_available=140,
                class_type="economy",
            ),
            Flight(
                origin="Ho Chi Minh City",
                destination="Singapore",
                airline="Vietnam Airlines",
                departure_time=datetime(2026, 4, 25, 22, 0),
                arrival_time=datetime(2026, 4, 26, 1, 10),
                price=195.00,
                seats_available=35,
                class_type="business",
            ),
            Flight(
                origin="Manila",
                destination="Kuala Lumpur",
                airline="Cebu Pacific",
                departure_time=datetime(2026, 4, 26, 5, 30),
                arrival_time=datetime(2026, 4, 26, 9, 0),
                price=99.00,
                seats_available=175,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Bangkok",
                airline="Bangkok Airways",
                departure_time=datetime(2026, 4, 27, 12, 0),
                arrival_time=datetime(2026, 4, 27, 13, 15),
                price=88.00,
                seats_available=55,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Jakarta",
                airline="Garuda Indonesia",
                departure_time=datetime(2026, 4, 28, 18, 45),
                arrival_time=datetime(2026, 4, 28, 20, 30),
                price=750.00,
                seats_available=10,
                class_type="first",
            ),
            Flight(
                origin="Phnom Penh",
                destination="Ho Chi Minh City",
                airline="Vietnam Airlines",
                departure_time=datetime(2026, 4, 29, 8, 0),
                arrival_time=datetime(2026, 4, 29, 9, 0),
                price=42.00,
                seats_available=90,
                class_type="economy",
            ),
            # Myanmar flights
            Flight(
                origin="Yangon",
                destination="Mandalay",
                airline="Myanmar National Airlines",
                departure_time=datetime(2026, 4, 10, 7, 0),
                arrival_time=datetime(2026, 4, 10, 8, 0),
                price=55.00,
                seats_available=60,
                class_type="economy",
            ),
            Flight(
                origin="Mandalay",
                destination="Yangon",
                airline="Myanmar National Airlines",
                departure_time=datetime(2026, 4, 14, 16, 0),
                arrival_time=datetime(2026, 4, 14, 17, 0),
                price=55.00,
                seats_available=45,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Bagan",
                airline="Air KBZ",
                departure_time=datetime(2026, 4, 11, 6, 30),
                arrival_time=datetime(2026, 4, 11, 7, 20),
                price=72.00,
                seats_available=38,
                class_type="economy",
            ),
            Flight(
                origin="Bagan",
                destination="Inle Lake",
                airline="Air KBZ",
                departure_time=datetime(2026, 4, 15, 9, 0),
                arrival_time=datetime(2026, 4, 15, 9, 45),
                price=68.00,
                seats_available=28,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Singapore",
                airline="Myanmar Airways International",
                departure_time=datetime(2026, 4, 12, 8, 30),
                arrival_time=datetime(2026, 4, 12, 12, 45),
                price=215.00,
                seats_available=70,
                class_type="economy",
            ),
            Flight(
                origin="Singapore",
                destination="Yangon",
                airline="Myanmar Airways International",
                departure_time=datetime(2026, 4, 18, 14, 0),
                arrival_time=datetime(2026, 4, 18, 17, 45),
                price=220.00,
                seats_available=55,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Kuala Lumpur",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 13, 10, 0),
                arrival_time=datetime(2026, 4, 13, 13, 30),
                price=138.00,
                seats_available=120,
                class_type="economy",
            ),
            Flight(
                origin="Kuala Lumpur",
                destination="Yangon",
                airline="AirAsia",
                departure_time=datetime(2026, 4, 20, 7, 15),
                arrival_time=datetime(2026, 4, 20, 10, 45),
                price=132.00,
                seats_available=95,
                class_type="economy",
            ),
            Flight(
                origin="Mandalay",
                destination="Chiang Mai",
                airline="Bangkok Airways",
                departure_time=datetime(2026, 4, 16, 11, 0),
                arrival_time=datetime(2026, 4, 16, 12, 15),
                price=110.00,
                seats_available=30,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Bangkok",
                airline="Thai Airways",
                departure_time=datetime(2026, 4, 22, 9, 30),
                arrival_time=datetime(2026, 4, 22, 11, 0),
                price=145.00,
                seats_available=40,
                class_type="economy",
            ),
            Flight(
                origin="Yangon",
                destination="Bangkok",
                airline="Myanmar Airways International",
                departure_time=datetime(2026, 4, 25, 7, 0),
                arrival_time=datetime(2026, 4, 25, 8, 30),
                price=320.00,
                seats_available=8,
                class_type="business",
            ),
        ]
        session.add_all(flights)

        # Hotels
        hotels = [
            Hotel(
                name="Mandarin Oriental Bangkok",
                location="48 Oriental Ave, Bang Rak",
                city="Bangkok",
                stars=5,
                price_per_night=320.00,
                rooms_available=12,
                amenities="pool,spa,gym,restaurant,bar,river view",
            ),
            Hotel(
                name="The Mulia Bali",
                location="Jl. Raya Nusa Dua Selatan",
                city="Bali",
                stars=5,
                price_per_night=450.00,
                rooms_available=8,
                amenities="private beach,pool,spa,gym,4 restaurants,butler service",
            ),
            Hotel(
                name="Marina Bay Sands",
                location="10 Bayfront Ave",
                city="Singapore",
                stars=5,
                price_per_night=550.00,
                rooms_available=5,
                amenities="infinity pool,casino,mall,3 restaurants,sky park",
            ),
            Hotel(
                name="Trisara Phuket",
                location="60/1 Moo 6, Srisoonthorn Rd",
                city="Phuket",
                stars=5,
                price_per_night=380.00,
                rooms_available=10,
                amenities="private pool villas,beach,spa,restaurant,snorkeling",
            ),
            Hotel(
                name="The RuMa Hotel Kuala Lumpur",
                location="7 Jalan Kia Peng",
                city="Kuala Lumpur",
                stars=5,
                price_per_night=280.00,
                rooms_available=18,
                amenities="pool,spa,gym,restaurant,bar,KLCC views",
            ),
            Hotel(
                name="ibis Bangkok Sukhumvit",
                location="27 Sukhumvit Soi 4",
                city="Bangkok",
                stars=3,
                price_per_night=65.00,
                rooms_available=45,
                amenities="wifi,breakfast,24h reception",
            ),
            # New hotels
            Hotel(
                name="Sala Lanna Chiang Mai",
                location="49/9 Charoenrat Rd, Wat Ket",
                city="Chiang Mai",
                stars=4,
                price_per_night=115.00,
                rooms_available=22,
                amenities="pool,restaurant,bar,bicycle rental,river view,wifi",
            ),
            Hotel(
                name="The Hoi An Riverside Retreat",
                location="Cam Thanh Village, Hoi An",
                city="Hoi An",
                stars=4,
                price_per_night=98.00,
                rooms_available=16,
                amenities="pool,spa,breakfast,kayaking,cycling,wifi",
            ),
            Hotel(
                name="Nusa Dua Beach Villas",
                location="Jl. Pantai Mengiat, Nusa Dua",
                city="Bali",
                stars=4,
                price_per_night=185.00,
                rooms_available=14,
                amenities="private pool,beach access,spa,restaurant,wifi",
            ),
            Hotel(
                name="Patong Bay Guesthouse",
                location="118/3 Thaweewong Rd, Patong",
                city="Phuket",
                stars=2,
                price_per_night=28.00,
                rooms_available=30,
                amenities="wifi,fan rooms,shared kitchen,beach nearby",
            ),
            Hotel(
                name="The Straits Boutique Singapore",
                location="22 Stanley St, Central",
                city="Singapore",
                stars=4,
                price_per_night=210.00,
                rooms_available=20,
                amenities="gym,rooftop bar,restaurant,concierge,wifi",
            ),
            Hotel(
                name="Khaosan Road Hostel",
                location="84 Khaosan Rd, Banglamphu",
                city="Bangkok",
                stars=2,
                price_per_night=22.00,
                rooms_available=50,
                amenities="wifi,bar,24h reception,lockers,shared bathroom",
            ),
            Hotel(
                name="Chiangmai Heritage House",
                location="7 Moonmuang Rd, Old City",
                city="Chiang Mai",
                stars=3,
                price_per_night=55.00,
                rooms_available=18,
                amenities="pool,breakfast,wifi,bicycle rental,garden",
            ),
            Hotel(
                name="KL Sentral Transit Hotel",
                location="Jalan Stesen Sentral 5, Brickfields",
                city="Kuala Lumpur",
                stars=3,
                price_per_night=70.00,
                rooms_available=40,
                amenities="gym,restaurant,wifi,express check-in,24h reception",
            ),
            Hotel(
                name="Seminyak Garden Suites",
                location="Jl. Drupadi 18, Seminyak",
                city="Bali",
                stars=3,
                price_per_night=60.00,
                rooms_available=25,
                amenities="pool,wifi,breakfast,shuttle,garden",
            ),
            Hotel(
                name="Lantern Hoi An Hotel",
                location="34 Le Loi St, Hoi An Old Town",
                city="Hoi An",
                stars=3,
                price_per_night=45.00,
                rooms_available=20,
                amenities="pool,breakfast,wifi,laundry,bicycle rental",
            ),
            Hotel(
                name="Phuket Grand Seaview",
                location="123 Kata Beach Rd, Kata",
                city="Phuket",
                stars=4,
                price_per_night=140.00,
                rooms_available=35,
                amenities="pool,spa,gym,2 restaurants,beach shuttle,wifi",
            ),
            Hotel(
                name="Orchard Residences Singapore",
                location="238 Orchard Blvd, Orchard",
                city="Singapore",
                stars=5,
                price_per_night=480.00,
                rooms_available=7,
                amenities="infinity pool,spa,butler,3 restaurants,concierge,gym",
            ),
            Hotel(
                name="Nimman Chic Chiang Mai",
                location="Nimmanhemin Rd Soi 1",
                city="Chiang Mai",
                stars=4,
                price_per_night=88.00,
                rooms_available=28,
                amenities="rooftop pool,gym,cafe,wifi,co-working space",
            ),
            Hotel(
                name="Bukit Bintang Budget Inn",
                location="Jl. Bukit Bintang 44, KL",
                city="Kuala Lumpur",
                stars=2,
                price_per_night=25.00,
                rooms_available=48,
                amenities="wifi,air conditioning,24h reception,near metro",
            ),
            Hotel(
                name="Hoi An Ancient Town B&B",
                location="12 Tran Phu St, Hoi An",
                city="Hoi An",
                stars=2,
                price_per_night=32.00,
                rooms_available=12,
                amenities="wifi,breakfast,bicycle rental,garden terrace",
            ),
            # Myanmar hotels
            Hotel(
                name="Belmond Governor's Residence",
                location="35 Taw Win Rd, Dagon Township",
                city="Yangon",
                stars=5,
                price_per_night=310.00,
                rooms_available=6,
                amenities="pool,spa,restaurant,colonial architecture,garden,bar,butler service",
            ),
            Hotel(
                name="Strand Hotel Yangon",
                location="92 Strand Rd, Kyauktada Township",
                city="Yangon",
                stars=5,
                price_per_night=280.00,
                rooms_available=9,
                amenities="restaurant,bar,spa,heritage building,concierge,wifi",
            ),
            Hotel(
                name="Chatrium Hotel Royal Lake Yangon",
                location="40 Natmauk Rd, Tamwe Township",
                city="Yangon",
                stars=5,
                price_per_night=175.00,
                rooms_available=18,
                amenities="pool,spa,gym,3 restaurants,bar,lake view,wifi",
            ),
            Hotel(
                name="Yoma Cherry Lodge Yangon",
                location="49 Yaw Min Gyi Rd, Dagon Township",
                city="Yangon",
                stars=3,
                price_per_night=48.00,
                rooms_available=32,
                amenities="wifi,breakfast,restaurant,24h reception,air conditioning",
            ),
            Hotel(
                name="Agga Backpacker Hostel Yangon",
                location="228 Sule Pagoda Rd, Kyauktada",
                city="Yangon",
                stars=2,
                price_per_night=15.00,
                rooms_available=40,
                amenities="wifi,shared kitchen,lockers,24h reception,city center",
            ),
            Hotel(
                name="Bagan Lodge",
                location="Near Dhammayangyi Temple, Bagan",
                city="Bagan",
                stars=5,
                price_per_night=260.00,
                rooms_available=10,
                amenities="pool,spa,restaurant,temple views,bicycle rental,sunset terrace,wifi",
            ),
            Hotel(
                name="Thazin Garden Hotel Bagan",
                location="Myinkaba Village, Old Bagan",
                city="Bagan",
                stars=4,
                price_per_night=120.00,
                rooms_available=22,
                amenities="pool,restaurant,bar,garden,bicycle rental,wifi,temple tours",
            ),
            Hotel(
                name="Bagan Thiripyitsaya Sanctuary Resort",
                location="Old Bagan Archaeological Zone",
                city="Bagan",
                stars=4,
                price_per_night=155.00,
                rooms_available=16,
                amenities="pool,restaurant,spa,Irrawaddy river view,wifi,bicycle rental",
            ),
            Hotel(
                name="Ostello Bello Bagan",
                location="Nyaung U Village, Bagan",
                city="Bagan",
                stars=2,
                price_per_night=18.00,
                rooms_available=25,
                amenities="wifi,breakfast,bicycle rental,common area,rooftop",
            ),
            Hotel(
                name="Mandalar Htun Hotel Mandalay",
                location="26th St & 78th St, Chan Aye Tharzan",
                city="Mandalay",
                stars=4,
                price_per_night=95.00,
                rooms_available=28,
                amenities="pool,restaurant,gym,wifi,airport shuttle,city views",
            ),
            Hotel(
                name="Rupar Mandalar Resort",
                location="Near U Bein Bridge, Amarapura",
                city="Mandalay",
                stars=5,
                price_per_night=195.00,
                rooms_available=12,
                amenities="pool,spa,restaurant,U Bein bridge view,garden,wifi",
            ),
            Hotel(
                name="ET Hotel Mandalay",
                location="83rd St 26/27, Chanmyathazi",
                city="Mandalay",
                stars=3,
                price_per_night=38.00,
                rooms_available=35,
                amenities="wifi,restaurant,24h reception,air conditioning,breakfast",
            ),
            Hotel(
                name="Inle Princess Resort",
                location="Magyizin Village, Inle Lake",
                city="Inle Lake",
                stars=5,
                price_per_night=290.00,
                rooms_available=8,
                amenities="overwater bungalows,spa,restaurant,lake views,boat tours,wifi",
            ),
            Hotel(
                name="Paramount Inle Resort",
                location="Nyaung Shwe Township, Inle Lake",
                city="Inle Lake",
                stars=4,
                price_per_night=130.00,
                rooms_available=18,
                amenities="pool,restaurant,boat transfer,spa,wifi,lake views",
            ),
            Hotel(
                name="Gypsy Inn Nyaung Shwe",
                location="Yone Gyi Rd, Nyaung Shwe",
                city="Inle Lake",
                stars=2,
                price_per_night=22.00,
                rooms_available=20,
                amenities="wifi,breakfast,bicycle rental,garden,boat tour booking",
            ),
        ]
        session.add_all(hotels)

        # Activities
        activities = [
            Activity(
                name="Grand Palace & Wat Phra Kaew Tour",
                city="Bangkok",
                description="Guided tour of the iconic Grand Palace complex and Temple of the Emerald Buddha.",
                duration_hours=3.0,
                price=35.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Ubud Rice Terrace Cycling",
                city="Bali",
                description="Cycle through stunning Tegallalang rice terraces with a local guide and traditional lunch.",
                duration_hours=5.0,
                price=55.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Singapore Street Food Night Tour",
                city="Singapore",
                description="Explore hawker centres and hidden eateries with a local food expert.",
                duration_hours=3.5,
                price=80.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Phi Phi Island Snorkeling Day Trip",
                city="Phuket",
                description="Full-day speedboat tour to Phi Phi Islands with snorkeling, kayaking, and beach time.",
                duration_hours=9.0,
                price=75.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Batu Caves & KL City Highlights",
                city="Kuala Lumpur",
                description="Visit the famous Batu Caves Hindu temple and explore KL's colonial quarter.",
                duration_hours=6.0,
                price=45.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Bali Volcano Sunrise Trek",
                city="Bali",
                description="Night trek to the summit of Mount Batur to watch the sunrise over the caldera.",
                duration_hours=7.0,
                price=65.00,
                category="adventure",
                availability="daily",
            ),
            # New activities
            Activity(
                name="Muay Thai Training Class",
                city="Bangkok",
                description="Two-hour beginner Muay Thai session with a professional trainer at a local gym.",
                duration_hours=2.0,
                price=25.00,
                category="adventure",
                availability="monday-friday",
            ),
            Activity(
                name="Chiang Mai Night Bazaar Food Tour",
                city="Chiang Mai",
                description="Walk the famous Night Bazaar sampling khao soi, sai oua sausage, and mango sticky rice.",
                duration_hours=3.0,
                price=30.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Traditional Thai Cooking Class",
                city="Chiang Mai",
                description="Half-day class at a family farm: market visit, grow your own herbs, cook 5 dishes.",
                duration_hours=4.0,
                price=40.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Hoi An Lantern Making Workshop",
                city="Hoi An",
                description="Learn to craft a traditional silk lantern from a local artisan in the Old Town.",
                duration_hours=2.0,
                price=18.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Hoi An Boat Ride & Cooking Class",
                city="Hoi An",
                description="Cruise the Thu Bon River, visit a herb island, then cook authentic Vietnamese dishes.",
                duration_hours=6.0,
                price=55.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Singapore Sentosa Island Beach Club",
                city="Singapore",
                description="Full-day access to Sentosa's beach club with water slides, kayaking, and a beach bar.",
                duration_hours=8.0,
                price=65.00,
                category="water sports",
                availability="daily",
            ),
            Activity(
                name="Balinese Spa & Wellness Ritual",
                city="Bali",
                description="Three-hour traditional Balinese spa ritual: scrub, massage, and flower bath.",
                duration_hours=3.0,
                price=50.00,
                category="wellness",
                availability="daily",
            ),
            Activity(
                name="Seminyak Sunset Surf Lesson",
                city="Bali",
                description="Two-hour beginner surf lesson on Seminyak Beach with certified instructors.",
                duration_hours=2.0,
                price=35.00,
                category="water sports",
                availability="daily",
            ),
            Activity(
                name="Phuket Rooftop Bar Nightlife Tour",
                city="Phuket",
                description="Guided nightlife crawl hitting 4 rooftop bars in Patong with a local host.",
                duration_hours=4.0,
                price=45.00,
                category="nightlife",
                availability="weekends",
            ),
            Activity(
                name="Elephant Sanctuary Half-Day Visit",
                city="Chiang Mai",
                description="Ethical elephant experience: feed, bathe, and walk with rescued elephants in the jungle.",
                duration_hours=4.0,
                price=85.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Kuala Lumpur Street Art Walk",
                city="Kuala Lumpur",
                description="Self-guided walking tour of Klang Valley's vibrant murals with a printed map and audio guide.",
                duration_hours=2.0,
                price=12.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Ho Chi Minh City Cu Chi Tunnels",
                city="Ho Chi Minh City",
                description="Half-day guided visit to the historic Cu Chi Tunnel network used during the Vietnam War.",
                duration_hours=4.0,
                price=28.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Mekong Delta River Cruise",
                city="Ho Chi Minh City",
                description="Full-day boat tour through the Mekong Delta, visiting floating markets and rice paddies.",
                duration_hours=8.0,
                price=42.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Hanoi Old Quarter Walking Tour",
                city="Hanoi",
                description="Explore the 36 ancient trade streets of Hanoi's Old Quarter with a knowledgeable local guide.",
                duration_hours=3.0,
                price=20.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Halong Bay Sunset Kayaking",
                city="Hanoi",
                description="Day trip to Halong Bay with guided kayaking through limestone caves at sunset.",
                duration_hours=8.0,
                price=95.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Singapore Night Safari",
                city="Singapore",
                description="Guided tram and walking tour through the world's first nocturnal wildlife park.",
                duration_hours=3.0,
                price=55.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Bali Rice Paddy Yoga Retreat",
                city="Bali",
                description="Morning yoga session overlooking Ubud's terraced rice fields, followed by a smoothie bowl.",
                duration_hours=2.0,
                price=22.00,
                category="wellness",
                availability="monday-friday",
            ),
            Activity(
                name="Bangkok Rooftop Bar Experience",
                city="Bangkok",
                description="Sunset drinks at one of Bangkok's iconic open-air rooftop bars with city panorama views.",
                duration_hours=2.0,
                price=35.00,
                category="nightlife",
                availability="daily",
            ),
            Activity(
                name="Phuket James Bond Island Tour",
                city="Phuket",
                description="Speedboat trip to Phang Nga Bay and the iconic Koh Tapu rock with sea canoeing.",
                duration_hours=6.0,
                price=68.00,
                category="adventure",
                availability="daily",
            ),
            # Myanmar activities
            Activity(
                name="Shwedagon Pagoda Sunset Tour",
                city="Yangon",
                description="Guided tour of Myanmar's most sacred Buddhist site as the golden stupa glows at sunset. Includes dress code briefing and entry fee.",
                duration_hours=2.5,
                price=22.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Yangon Colonial Quarter Walking Tour",
                city="Yangon",
                description="Walk through Yangon's UNESCO-listed downtown exploring British colonial architecture, hidden temples, and the vibrant Chinatown.",
                duration_hours=3.0,
                price=18.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Yangon Street Food Night Walk",
                city="Yangon",
                description="Taste mohinga fish noodle soup, tea leaf salad, samosas, and grilled skewers at the city's best street stalls with a local foodie guide.",
                duration_hours=3.0,
                price=25.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="Circular Train Ride Yangon",
                city="Yangon",
                description="Three-hour loop on the famous Yangon circular train — a window into daily local life passing markets, monasteries, and countryside.",
                duration_hours=3.0,
                price=8.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Bagan Temple E-Bike Sunrise Tour",
                city="Bagan",
                description="Ride an electric bike through the ancient plains at dawn, watching the sun rise over 2,000 pagodas and temples in golden mist.",
                duration_hours=4.0,
                price=30.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Bagan Hot Air Balloon Ride",
                city="Bagan",
                description="Iconic sunrise hot air balloon flight over the Bagan archaeological zone with champagne breakfast on landing.",
                duration_hours=3.0,
                price=360.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Bagan Archaeological Zone Guided Tour",
                city="Bagan",
                description="In-depth guided tour of Ananda Temple, Htilominlo, Sulamani, and Dhammayangyi with a licensed archaeologist.",
                duration_hours=5.0,
                price=45.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Bagan Cooking Class & Village Visit",
                city="Bagan",
                description="Visit a local Bagan village, shop at the morning market, and cook a traditional Bamar meal of curry, laphet thoke, and sticky rice.",
                duration_hours=4.0,
                price=35.00,
                category="food",
                availability="daily",
            ),
            Activity(
                name="U Bein Bridge Sunset Boat Trip",
                city="Mandalay",
                description="Boat ride on Taungthaman Lake at golden hour for iconic views of the world's longest teak footbridge at sunset.",
                duration_hours=2.0,
                price=20.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Mandalay Hill & Monasteries Tour",
                city="Mandalay",
                description="Climb Mandalay Hill for panoramic views, then visit the gilded Mahamuni Buddha and teak Shwenandaw Monastery.",
                duration_hours=5.0,
                price=30.00,
                category="culture",
                availability="daily",
            ),
            Activity(
                name="Mandalay Gold Leaf Workshop",
                city="Mandalay",
                description="Watch craftsmen hand-beat gold into wafer-thin leaf used to adorn Buddha images, and try it yourself.",
                duration_hours=1.5,
                price=12.00,
                category="culture",
                availability="monday-friday",
            ),
            Activity(
                name="Inle Lake Full-Day Boat Tour",
                city="Inle Lake",
                description="Boat through the floating gardens, visit leg-rowing fishermen, the Phaung Daw Oo Pagoda, and a traditional weaving village.",
                duration_hours=7.0,
                price=38.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Inle Lake Kayaking & Village Homestay",
                city="Inle Lake",
                description="Kayak through quiet channels away from tourist boats, stop at a minority village, and share a home-cooked meal with a local family.",
                duration_hours=6.0,
                price=55.00,
                category="adventure",
                availability="daily",
            ),
            Activity(
                name="Inle Lake Sunrise Photography Tour",
                city="Inle Lake",
                description="Early morning boat tour to capture the famous silhouette of leg-rowing fishermen in the mist at first light.",
                duration_hours=3.0,
                price=28.00,
                category="nature",
                availability="daily",
            ),
            Activity(
                name="Inle Traditional Shan Cooking Class",
                city="Inle Lake",
                description="Learn to cook Shan-style tofu, tomato salad, and rice noodle soup in a lakeside kitchen overlooking the water.",
                duration_hours=3.5,
                price=32.00,
                category="food",
                availability="daily",
            ),
        ]
        session.add_all(activities)

        # Transport
        transports = [
            Transport(
                type="ferry",
                origin="Singapore",
                destination="Batam",
                price=28.00,
                capacity=200,
                departure_time=datetime(2026, 4, 10, 9, 0),
                arrival_time=datetime(2026, 4, 10, 10, 0),
            ),
            Transport(
                type="train",
                origin="Bangkok",
                destination="Chiang Mai",
                price=22.00,
                capacity=120,
                departure_time=datetime(2026, 4, 11, 18, 0),
                arrival_time=datetime(2026, 4, 12, 7, 0),
            ),
            Transport(
                type="bus",
                origin="Kuala Lumpur",
                destination="Singapore",
                price=18.00,
                capacity=45,
                departure_time=datetime(2026, 4, 13, 8, 0),
                arrival_time=datetime(2026, 4, 13, 13, 30),
            ),
            Transport(
                type="car",
                origin="Bali Airport",
                destination="Ubud",
                price=25.00,
                capacity=4,
                departure_time=datetime(2026, 4, 14, 15, 0),
                arrival_time=datetime(2026, 4, 14, 16, 30),
            ),
            Transport(
                type="ferry",
                origin="Phuket",
                destination="Koh Samui",
                price=45.00,
                capacity=150,
                departure_time=datetime(2026, 4, 16, 7, 30),
                arrival_time=datetime(2026, 4, 16, 13, 0),
            ),
            # New transport
            Transport(
                type="bus",
                origin="Bangkok",
                destination="Pattaya",
                price=5.00,
                capacity=45,
                departure_time=datetime(2026, 4, 10, 7, 0),
                arrival_time=datetime(2026, 4, 10, 9, 0),
            ),
            Transport(
                type="ferry",
                origin="Bali",
                destination="Lombok",
                price=12.00,
                capacity=60,
                departure_time=datetime(2026, 4, 11, 8, 30),
                arrival_time=datetime(2026, 4, 11, 10, 30),
            ),
            Transport(
                type="train",
                origin="Singapore",
                destination="Kuala Lumpur",
                price=35.00,
                capacity=200,
                departure_time=datetime(2026, 4, 12, 10, 0),
                arrival_time=datetime(2026, 4, 12, 14, 30),
            ),
            Transport(
                type="ferry",
                origin="Phuket",
                destination="Krabi",
                price=15.00,
                capacity=50,
                departure_time=datetime(2026, 4, 13, 9, 0),
                arrival_time=datetime(2026, 4, 13, 11, 0),
            ),
            Transport(
                type="minivan",
                origin="Chiang Mai",
                destination="Chiang Rai",
                price=8.00,
                capacity=12,
                departure_time=datetime(2026, 4, 14, 7, 30),
                arrival_time=datetime(2026, 4, 14, 10, 30),
            ),
            Transport(
                type="bus",
                origin="Ho Chi Minh City",
                destination="Phnom Penh",
                price=12.00,
                capacity=45,
                departure_time=datetime(2026, 4, 15, 6, 30),
                arrival_time=datetime(2026, 4, 15, 12, 0),
            ),
            Transport(
                type="minivan",
                origin="Hanoi",
                destination="Ha Long Bay",
                price=10.00,
                capacity=16,
                departure_time=datetime(2026, 4, 16, 8, 0),
                arrival_time=datetime(2026, 4, 16, 11, 30),
            ),
            Transport(
                type="car",
                origin="Singapore Airport",
                destination="Singapore City",
                price=28.00,
                capacity=4,
                departure_time=datetime(2026, 4, 17, 14, 0),
                arrival_time=datetime(2026, 4, 17, 14, 45),
            ),
            Transport(
                type="bus",
                origin="Kuala Lumpur",
                destination="Penang",
                price=14.00,
                capacity=45,
                departure_time=datetime(2026, 4, 18, 9, 0),
                arrival_time=datetime(2026, 4, 18, 13, 30),
            ),
            Transport(
                type="ferry",
                origin="Koh Samui",
                destination="Koh Phangan",
                price=8.00,
                capacity=40,
                departure_time=datetime(2026, 4, 19, 11, 0),
                arrival_time=datetime(2026, 4, 19, 11, 45),
            ),
            Transport(
                type="train",
                origin="Bangkok",
                destination="Ayutthaya",
                price=2.00,
                capacity=100,
                departure_time=datetime(2026, 4, 20, 7, 0),
                arrival_time=datetime(2026, 4, 20, 8, 30),
            ),
            Transport(
                type="minivan",
                origin="Bali Airport",
                destination="Seminyak",
                price=15.00,
                capacity=8,
                departure_time=datetime(2026, 4, 21, 16, 0),
                arrival_time=datetime(2026, 4, 21, 16, 45),
            ),
            Transport(
                type="bus",
                origin="Hoi An",
                destination="Da Nang",
                price=3.00,
                capacity=30,
                departure_time=datetime(2026, 4, 22, 8, 30),
                arrival_time=datetime(2026, 4, 22, 9, 15),
            ),
            Transport(
                type="ferry",
                origin="Langkawi",
                destination="Penang",
                price=22.00,
                capacity=55,
                departure_time=datetime(2026, 4, 23, 10, 30),
                arrival_time=datetime(2026, 4, 23, 13, 0),
            ),
            Transport(
                type="car",
                origin="Phuket Airport",
                destination="Patong Beach",
                price=18.00,
                capacity=4,
                departure_time=datetime(2026, 4, 24, 13, 15),
                arrival_time=datetime(2026, 4, 24, 14, 0),
            ),
            Transport(
                type="minivan",
                origin="Ho Chi Minh City",
                destination="Mui Ne",
                price=9.00,
                capacity=16,
                departure_time=datetime(2026, 4, 25, 7, 0),
                arrival_time=datetime(2026, 4, 25, 11, 30),
            ),
            Transport(
                type="bus",
                origin="Bangkok",
                destination="Kanchanaburi",
                price=6.00,
                capacity=45,
                departure_time=datetime(2026, 4, 26, 6, 30),
                arrival_time=datetime(2026, 4, 26, 9, 0),
            ),
            # Myanmar transport
            Transport(
                type="car",
                origin="Yangon Airport",
                destination="Yangon City",
                price=12.00,
                capacity=4,
                departure_time=datetime(2026, 4, 10, 10, 0),
                arrival_time=datetime(2026, 4, 10, 11, 0),
            ),
            Transport(
                type="bus",
                origin="Yangon",
                destination="Mandalay",
                price=14.00,
                capacity=45,
                departure_time=datetime(2026, 4, 11, 20, 0),
                arrival_time=datetime(2026, 4, 12, 7, 0),
            ),
            Transport(
                type="train",
                origin="Yangon",
                destination="Mandalay",
                price=18.00,
                capacity=100,
                departure_time=datetime(2026, 4, 12, 6, 0),
                arrival_time=datetime(2026, 4, 12, 21, 0),
            ),
            Transport(
                type="bus",
                origin="Mandalay",
                destination="Bagan",
                price=8.00,
                capacity=35,
                departure_time=datetime(2026, 4, 13, 7, 0),
                arrival_time=datetime(2026, 4, 13, 12, 0),
            ),
            Transport(
                type="bus",
                origin="Yangon",
                destination="Bagan",
                price=16.00,
                capacity=45,
                departure_time=datetime(2026, 4, 14, 19, 0),
                arrival_time=datetime(2026, 4, 15, 5, 30),
            ),
            Transport(
                type="bus",
                origin="Bagan",
                destination="Inle Lake",
                price=10.00,
                capacity=30,
                departure_time=datetime(2026, 4, 16, 8, 0),
                arrival_time=datetime(2026, 4, 16, 16, 0),
            ),
            Transport(
                type="minivan",
                origin="Mandalay",
                destination="Inle Lake",
                price=12.00,
                capacity=10,
                departure_time=datetime(2026, 4, 17, 7, 0),
                arrival_time=datetime(2026, 4, 17, 14, 30),
            ),
            Transport(
                type="bus",
                origin="Inle Lake",
                destination="Yangon",
                price=16.00,
                capacity=40,
                departure_time=datetime(2026, 4, 19, 20, 0),
                arrival_time=datetime(2026, 4, 20, 8, 0),
            ),
            Transport(
                type="car",
                origin="Mandalay Airport",
                destination="Mandalay City",
                price=10.00,
                capacity=4,
                departure_time=datetime(2026, 4, 16, 12, 30),
                arrival_time=datetime(2026, 4, 16, 13, 15),
            ),
            Transport(
                type="minivan",
                origin="Nyaung U",
                destination="Bagan Temples",
                price=5.00,
                capacity=8,
                departure_time=datetime(2026, 4, 15, 5, 30),
                arrival_time=datetime(2026, 4, 15, 6, 0),
            ),
            Transport(
                type="ferry",
                origin="Mandalay",
                destination="Bagan",
                price=35.00,
                capacity=80,
                departure_time=datetime(2026, 4, 18, 5, 30),
                arrival_time=datetime(2026, 4, 18, 17, 0),
            ),
        ]
        session.add_all(transports)

        session.commit()

        flight_count = len(session.exec(select(Flight)).all())
        hotel_count = len(session.exec(select(Hotel)).all())
        activity_count = len(session.exec(select(Activity)).all())
        transport_count = len(session.exec(select(Transport)).all())
        print(f"Seeded: {flight_count} flights, {hotel_count} hotels, {activity_count} activities, {transport_count} transports")


if __name__ == "__main__":
    seed()
